### ISSUE TITLE
1.10 Server Crash - Skeleton kills don't drop anything / crash

### ISSUE THREAD

**Issue by MachinegunMarty** [xLionel775/AgriculturalExpansion#8]
With the latest 3 versions on forge 12.18.0.1986 server + client: 
When killing a skeleton or when he dies from burning in the sun, the server crashes.
Client has no problem.

[01:36:21] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.entity.monster.EntitySkeleton.func_82202_m()I
    at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_91]
    at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_91]
    at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.monster.EntitySkeleton.func_82202_m()I
    at com.agriculturalexpansion.handler.MobDrops.onMobDrops(MobDrops.java:94) ~[MobDrops.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_13_MobDrops_onMobDrops_LivingDropsEvent.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:68) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:159) ~[EventBus.class:?]
    at net.minecraftforge.common.ForgeHooks.onLivingDrops(ForgeHooks.java:509) ~[ForgeHooks.class:?]
    at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1090) ~[sf.class:?]
    at net.minecraft.entity.monster.EntitySkeleton.func_70645_a(SourceFile:199) ~[zd.class:?]
    at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:970) ~[sf.class:?]
    at net.minecraft.entity.monster.EntityMob.func_70097_a(SourceFile:73) ~[yx.class:?]
    at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1293) ~[zs.class:?]
    at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java:1222) ~[lu.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1040) ~[me.class:?]
    at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:68) ~[iu.class:?]
    at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:12) ~[iu.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_91]
    at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_91]
    at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
    ... 5 more
[01:40:09] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:715) ~[MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) ~[ld.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.monster.EntitySkeleton.func_82202_m()I
    at com.agriculturalexpansion.handler.MobDrops.onMobDrops(MobDrops.java:94) ~[MobDrops.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_13_MobDrops_onMobDrops_LivingDropsEvent.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:68) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:159) ~[EventBus.class:?]
    at net.minecraftforge.common.ForgeHooks.onLivingDrops(ForgeHooks.java:509) ~[ForgeHooks.class:?]
    at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1090) ~[sf.class:?]
    at net.minecraft.entity.monster.EntitySkeleton.func_70645_a(SourceFile:199) ~[zd.class:?]
    at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:970) ~[sf.class:?]
    at net.minecraft.entity.monster.EntityMob.func_70097_a(SourceFile:73) ~[yx.class:?]
    at net.minecraft.entity.Entity.func_70030_z(Entity.java:458) ~[rw.class:?]
    at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:216) ~[sf.class:?]
    at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:208) ~[sg.class:?]
    at net.minecraft.entity.Entity.func_70071_h_(Entity.java:359) ~[rw.class:?]
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1938) ~[sf.class:?]
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) ~[sg.class:?]
    at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:52) ~[yx.class:?]
    at net.minecraft.world.World.func_72866_a(World.java:1955) ~[aid.class:?]
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837) ~[ls.class:?]
    at net.minecraft.world.World.func_72870_g(World.java:1925) ~[aid.class:?]
    at net.minecraft.world.World.func_72939_s(World.java:1748) ~[aid.class:?]
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618) ~[ls.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?]
    ... 4 more
[01:40:09] [Server thread/ERROR]: This crash report has been saved to: C:\Minecraft\Marty's World 2016 - 1.10.\crash-reports\crash-2016-06-25_01.40.09-server.txt
[01:40:09] [Server thread/INFO]: Stopping server
[01:40:09] [Server thread/INFO]: Saving players
[01:40:09] [Server thread/INFO]: Saving worlds

**Comment by ionelaipatioaei** [comment]
Fixed in beta 1.1.13-mc1.10, now for the wither chunk you need to kill Wither Boss(10% chance to drop) instead of Wither Skeleton.
